# Generated by Django 3.2.3 on 2023-04-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('marca', models.CharField(default=None, max_length=50)),
                ('modelo', models.CharField(default=None, max_length=100)),
                ('precio', models.FloatField(default=None)),
                ('talla', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cascos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('marca', models.CharField(default=None, max_length=50)),
                ('modelo', models.CharField(default=None, max_length=100)),
                ('precio', models.FloatField(default=None)),
                ('talla', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cleats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('marca', models.CharField(default=None, max_length=50)),
                ('modelo', models.CharField(default=None, max_length=100)),
                ('precio', models.FloatField(default=None)),
                ('talla', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
