# Generated by Django 3.2.3 on 2023-05-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascos',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cleats',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
