# Generated by Django 3.2.3 on 2023-05-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0003_auto_20230522_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascos',
            name='image',
            field=models.ImageField(upload_to='images_cascos/'),
        ),
    ]
